# Generated by Django 3.0.8 on 2021-06-24 14:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menu',
            options={'verbose_name': 'Menu', 'verbose_name_plural': 'Menus'},
        ),
        migrations.AlterModelOptions(
            name='opcion',
            options={'verbose_name': 'Opcion', 'verbose_name_plural': 'Opciones'},
        ),
        migrations.AddField(
            model_name='menu',
            name='titulo',
            field=models.CharField(default='Menu del dia', max_length=30, verbose_name='Titulo del Menu'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='creado',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='enviar',
            field=models.BooleanField(default=False, verbose_name='Enviar recordatorio'),
        ),
    ]
