# Generated by Django 3.0.8 on 2021-06-24 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Menu', '0002_auto_20210624_0947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='enviar',
            field=models.BooleanField(default=False, verbose_name='Enviar recordatorio a Slack'),
        ),
        migrations.AlterField(
            model_name='ordenar',
            name='opcion',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='employer', to='Menu.Opcion'),
            preserve_default=False,
        ),
    ]
